services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "ny_taxi"
    volumes: 
      - pipeline_ny_taxi_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes: 
      - pipeline_pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"

volumes:
  pipeline_ny_taxi_postgres_data:
  pipeline_pgadmin_data: